Repository DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server, pull requests merged in 2022-10, with the labels that each got.

#3 [Docs] 이슈 템플릿 및 PR 템플릿 작성 (#1)
  .github/ISSUE_TEMPLATE/bugfix-template.md
  .github/ISSUE_TEMPLATE/configuration-templat.md
  .github/ISSUE_TEMPLATE/configuration-template.md
  .github/ISSUE_TEMPLATE/documentation-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/refactoring-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📕Documentation, 💨Leo

#5 Config/2 project config
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/ada/earthvalley/nier/NierApplication.java
  src/main/java/com/ada/earthvalley/nier/configs/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/ada/earthvalley/nier/NierApplicationTests.java
Labels: 💻Server, 💨Leo, 🛠Configuration

#10 [Doc] 데일리 스크럼 템플릿 작성 (#9)
  .github/ISSUE_TEMPLATE/daily-scrum-template.md
Labels: 📕Documentation
