Repository DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server, pull requests merged in 2022-11, with the labels that each got.

#26 [Feat] JwtAuthenticationFilter 생성 및 FilterChain에 등록 (#22)
  src/main/java/com/ada/earthvalley/yomojomo/auth/JwtAuthenticationFilter.java
  src/main/java/com/ada/earthvalley/yomojomo/configs/SecurityConfig.java
Labels: 👷Enhancement, 💻Server, 💨Leo

#31 [Feat] Exception Handler 및 ErrorResponse 정의 (#28)
  build.gradle
  src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorCode.java
  src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorInfo.java
  src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/ErrorResponse.java
  src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/YomojomoException.java
  src/main/java/com/ada/earthvalley/yomojomo/common/exceptions/handler/GlobalExceptionHandler.java
  src/test/java/com/ada/earthvalley/yomojomo/common/exceptions/ExceptionTestController.java
  src/test/java/com/ada/earthvalley/yomojomo/common/exceptions/GlobalExceptionHandlerTest.java
  src/test/java/com/ada/earthvalley/yomojomo/common/exceptions/errors/TestError.java
  src/test/java/com/ada/earthvalley/yomojomo/common/exceptions/errors/YomojomoTestException.java
Labels: 👷Enhancement, 💻Server, 💨Leo, 🧪Test

#33 [Chore] add spring data dynamodb
  build.gradle
Labels: 🛠Configuration

#44 [Feat] Entity의 id 컬럼 타입을 wrapper 클래스인 Long 으로 변경
  src/main/java/com/ada/earthvalley/yomojomo/YomojomoApplication.java
  src/main/java/com/ada/earthvalley/yomojomo/article/entities/Topic.java
  src/main/java/com/ada/earthvalley/yomojomo/auth/entities/RefreshToken.java
  src/main/java/com/ada/earthvalley/yomojomo/auth/entities/VendorResource.java
  src/main/java/com/ada/earthvalley/yomojomo/common/configs/JpaAuditingConfig.java
  src/main/java/com/ada/earthvalley/yomojomo/group/entities/Group.java
  src/main/java/com/ada/earthvalley/yomojomo/group/entities/GroupUser.java
  src/main/java/com/ada/earthvalley/yomojomo/group/entities/Invitation.java
  src/main/java/com/ada/earthvalley/yomojomo/nie/entities/Nie.java
  src/main/java/com/ada/earthvalley/yomojomo/nie/entities/NieProcess.java
  src/main/java/com/ada/earthvalley/yomojomo/user/entities/User.java
  src/main/java/com/ada/earthvalley/yomojomo/user/entities/UserTopic.java
  src/main/java/com/ada/earthvalley/yomojomo/word/entities/Word.java
  src/main/java/com/ada/earthvalley/yomojomo/word/entities/WordContext.java
  src/test/java/com/ada/earthvalley/yomojomo/common/baseEntities/BaseEntityTest.java
  src/test/java/com/ada/earthvalley/yomojomo/user/entities/UserTest.java
Labels: 🐞Bugfix, 📕Documentation, 👷Enhancement, 💻Server, 💨Leo, 🛠Configuration, 🧪Test

#66 Bugfix/65 jwt configurations
  .gitignore
  src/test/resources/application.yml
Labels: 🛠Configuration
